baseURL = 'https://kyle.cascade.family/'
languageCode = 'en-us'
title = 'kyle.cascade.family'
theme = 'poison'
publishDir = 'docs/'
[permalinks]
  post = '/:slug/'
#relativeURLs = true
#pygmentsCodeFences = true
paginate = 10
pluralizelisttitles = false

[params]
    brand = "Kyle Cascade"
    brand_image = "/images/KyleCascade.png"
    favicon = "/images/favicon-32x32.png"
    description = ''
    dark_mode = true

    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Subscribe", URL = "/subscribe/", HasChildren = false},
        {Name = "Recent Posts", URL = "/posts/", Pre = "", HasChildren = true, Limit = 5},
    ]

    github_url = "https://github.com/solarkennedy"
    linkedin_url = "https://www.linkedin.com/in/solarkennedy/"
    email_url = "mailto:kyle@cascade.family?Subject=Hi From Blog!"
    subscribe_url = "./subscribe"

    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "posts"

[taxonomies]
    series = 'series'
    tags = 'tags'
