baseURL = 'https://kyle.cascade.family/'
languageCode = 'en-us'
title = 'kyle.cascade.family'
theme = 'hugo-flex'
publishDir = 'docs/'
[permalinks]
  post = '/:slug/'
relativeURLs = true
pygmentsCodeFences = true

